services:
  - type: web
    name: smart-home-api
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm install
    startCommand: node server/index.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 7860
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: BACKEND_URL
        value: https://smart-home-api-l5dr.onrender.com
      - key: FRONTEND_URL
        value: https://tox1k332.github.io/smart-home-app
      - key: OPENWEATHER_API_KEY
        sync: false
