services:
  - type: web
    name: smart-home-api
    env: node
    region: frankfurt
    buildCommand: npm install
    startCommand: node server/index.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: BACKEND_URL
        value: https://smart-home-app-ea6f.onrender.com
      - key: JWT_SECRET
        value: smart-home-jwt-secret-key-change-in-production-2026
      - key: FRONTEND_URL
        value: https://smart-home-app52.netlify.app
      - key: OPENWEATHER_API_KEY
        value: 46954c93e53c9992375e3904ec3618a7
